### ISSUE TITLE
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by djadma** [discourse/mini_racer#98]
I'm trying to install mini_racer in ubuntu 16.04 but getting the error like `Failed to build gem native extension`
It's working fine with ruby 2.4.1 but not working with my ruby-version 2.3.0

```
Fetching mini_racer 0.2.0
Installing mini_racer 0.2.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/hp/.rvm/gems/ruby-2.3.0/gems/mini_racer-0.2.0/ext/mini_racer_extension
/home/hp/.rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20180820-3863-1jyuums.rb extconf.rb
checking for main() in -lpthread... yes
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/hp/.rvm/gems/ruby-2.3.0/extensions/x86_64-linux/2.3.0/mini_racer-0.2.0/mkmf.log

current directory: /home/hp/.rvm/gems/ruby-2.3.0/gems/mini_racer-0.2.0/ext/mini_racer_extension
make "DESTDIR=" clean

current directory: /home/hp/.rvm/gems/ruby-2.3.0/gems/mini_racer-0.2.0/ext/mini_racer_extension
make "DESTDIR="
compiling mini_racer_extension.cc
In file included from /home/hp/.rvm/rubies/ruby-2.3.0/include/ruby-2.3.0/ruby.h:33:0,
                 from mini_racer_extension.cc:2:
mini_racer_extension.cc: In function ‘VALUE protected_callback(VALUE)’:
/home/hp/.rvm/rubies/ruby-2.3.0/include/ruby-2.3.0/ruby/ruby.h:882:52: error: ‘__builtin_choose_expr’ was not declared in this scope
      OBJ_WB_UNPROTECT((VALUE)(obj)), ((VALUE)(obj))))
                                                    ^
/home/hp/.rvm/rubies/ruby-2.3.0/include/ruby-2.3.0/ruby/ruby.h:1039:48: note: in definition of macro ‘RARRAY_CONST_PTR’
 #define RARRAY_CONST_PTR(a) rb_array_const_ptr(a)
                                                ^
/home/hp/.rvm/rubies/ruby-2.3.0/include/ruby-2.3.0/ruby/ruby.h:1059:50: note: in expansion of macro ‘RB_OBJ_WB_UNPROTECT_FOR’
 #define RARRAY_PTR(a) ((VALUE *)RARRAY_CONST_PTR(RB_OBJ_WB_UNPROTECT_FOR(ARRAY, a)))
                                                  ^
mini_racer_extension.cc:850:9: note: in expansion of macro ‘RARRAY_PTR’
         RARRAY_PTR(data->ruby_args));
         ^
Makefile:206: recipe for target 'mini_racer_extension.o' failed
make: *** [mini_racer_extension.o] Error 1

make failed, exit code 2
````
Is there a solution?

**Comment by SamSaffron** [comment]
interesting ... can you try Ruby 2.3.7 ?

**Comment by ignisf** [comment]
Also, could you paste the output of `gcc -v`?

**Comment by djadma** [comment]
Yeah @SamSaffron, I have switch the ruby version 2.3.0 to 2.3.7 

@ignisf here is the data

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.10' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)
```
